---
driver:
  name: vagrant
  synced_folders:
    - [".", "/vagrant"]

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04
    driver:
      provider: vmware_fusion
     # box_url: https://vagrantcloud.com/parallels/boxes/ubuntu-14.04/versions/3/providers/parallels.box
    driver_config:
      network:
      - ["private_network", {ip: "192.168.102.10"}]

suites:
  - name: webapp
    run_list:
      - recipe[test-helper::default]
      - recipe[app::apt]
      - recipe[curl]
      - recipe[git]
      - recipe[app::php]
      - recipe[app::apache2]
      - recipe[app::mysql]
      - recipe[memcached]
      - recipe[app::mailcatcher]
      - recipe[composer]
      - recipe[phpunit]
      - recipe[app::nodejs]
      - recipe[app::phpmyadmin]
      - recipe[imagemagick]
