---
driver:
  name: vagrant
  synced_folders:
    - [".", "/vagrant"]

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04
    driver:
      box: vagrant box add ubuntu/trusty64
      #box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-14.04_provisionerless.box
#    driver:
#      provider: parallels
    driver_config:
      network:
      - ["private_network", {ip: "192.168.100.10"}]

suites:
  - name: webapp
    run_list:
      - recipe[test-helper::default]
      - recipe[app::apt]
      - recipe[curl]
      - recipe[git]
      - recipe[app::php-fpm]
      - recipe[app::apache2]
      - recipe[app::mysql]
      - recipe[memcached]
      - recipe[app::mailcatcher]
      - recipe[composer]
      - recipe[phpunit]
      - recipe[nodejs]