---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  solo_rb:
    ssl_verify_mode: verify_peer

platforms:
  - name: ubuntu-14.04
    driver:
      box: opscode-ubuntu-14.04
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-14.04_provisionerless.box
#    driver:
#      provider: parallels
    driver_config:
      network:
      - ["private_network", {ip: "33.33.33.11"}]
#      - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: webapp
    run_list:
      - recipe[app::apt]
      - recipe[curl]
      - recipe[app::apache2]
      - recipe[app::mysql]
    attributes:
      mysql:
        server_root_password: "root"