sonata_admin:
    security:
        handler: sonata.admin.security.handler.role

    dashboard:
        groups:
            sonata.admin.group.administration:
                label:           sonata_administration
                label_catalogue: SonataAdminBundle
                icon:            '<i class="fa fa-cogs"></i>'
                items:
                    - sonata.user.admin.user
sonata_user:
    #security_acl: true
    manager_type: orm
    class:
        user: App\DefaultBundle\Entity\User
        group: App\DefaultBundle\Entity\Group

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.admin.block.admin_list:
            contexts:   [admin]