default_homepage:
    path:     /
    defaults: { _controller: AppDefaultBundle:Default:index }

noscript:
    path:     /noscript/hide
    defaults: { _controller: AppDefaultBundle:Default:noscript }

tweets:
    path:     /tweets
    defaults: { _controller: AppDefaultBundle:Twitter:tweets }