default['apache']['version']           = '2.4'
default['apache']['user']              = 'vagrant'
default['apache']['group']             = 'vagrant'
default['apache']['contact']           = 'nick@linkstudios.co.uk'
default['apache']['config_name']       = 'nickphillips.co'